services:
  - type: web
    name: faceauthen-backend
    runtime: node
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22.16.0
      - key: DATABASE_URL
        sync: false
